# Navigation Links
#   To link a homepage section, use a hash `#` followed by the section ID.
#   The weight parameter defines the order that the links appear.

main:
  - name: Bio
    url: /#biography
    weight: 10
  - name: Experience and Education
    url: /#experience
    weight: 20
  - name: Projects
    url: /#projects
    weight: 30
  - name: Scientific Contributions 
    url: /#scientificcontributions 
    weight: 40
  - name: Distinctions  
    url: /#distinctions
    weight: 50
  - name: Blog
    url: /#blog
    weight: 60
  - name: Contact
    url: /#contact
    weight: 70
